services:
  - type: web
    name: fake-news-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false